package com.wsonoma.zipInfoService.util;

import com.wsonoma.zipInfoService.data.IOTypes;

public class IOConfigFactory {
	
	// This class provide a factory of currently available objects to be constructed based on property file.
	// When a new input/output is introduced, it can be easily generated by adding another case.
	
	public InputManager getInputHandler () {
		switch (IOConfigurations.inputType) {
			case IOTypes.FLAT_FILE:
				return new InputManagerFlatFileImpl();
			case IOTypes.DATABASE:
				return null;
			case IOTypes.DEMO:
				return new InputManagerDemoImpl();
		}
		return null;
	}
	
	public OutputManager getOutputHandler () {
		switch (IOConfigurations.outputType) {
		case IOTypes.FLAT_FILE:
			return new OutputManagerFlatFileImpl();
		case IOTypes.DATABASE:
			return null;
		}
		return null;
	}
	


}